user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzM2MjQ=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: kts_postgres
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.El6hzK1d5XLsP0T32gwLD_bIH7rZSbT1jGEE2_N8QBY9zNV5Nx919BFYDWCj4Dwoxot93hk2je5nwmOH-7m3kiGZbp6qQxnwnajHleVNyfaBaYQbU9F2_3ctE7vdXYBZpVeYU4gumAFXoRcIuuO1k1VjQPZNQfQg6_m3DRdwZpJO6Zgd6difQXjeLGJ2k3CP
  group_id: 215478952


