"""add_default

Revision ID: 98a6c4dfb809
Revises: 851a1d63cf64
Create Date: 2022-09-15 13:26:23.536021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a6c4dfb809'
down_revision = '851a1d63cf64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO settings (title, timeout) VALUES ('слова', 30)")
    op.execute("INSERT INTO settings (title, timeout) VALUES ('города', 30)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM settings WHERE title ='слова' OR title ='города' ")
    # ### end Alembic commands ###
